### ISSUE TITLE
seu <- ScaleData(seu, features = all.markers)

### ISSUE THREAD

**Issue by vijithaduke** [jianhong/cdQuPath#1]
seu <- ScaleData(seu, features = all.markers)
Warning: No layers found matching search pattern providedError in `ScaleData()`:
! No layer matching pattern 'data' found. Please run NormalizeData and retry
Backtrace:
 1. Seurat::ScaleData(seu, features = all.markers)
 2. Seurat:::ScaleData.Seurat(seu, features = all.markers)
 4. Seurat:::ScaleData.StdAssay(...)
> all.markers <- rownames(seu)
> seu <- ScaleData(seu, features = all.markers)
Warning: No layers found matching search pattern providedError in `ScaleData()`:
! No layer matching pattern 'data' found. Please run NormalizeData and retry
Backtrace:
 1. Seurat::ScaleData(seu, features = all.markers)
 2. Seurat:::ScaleData.Seurat(seu, features = all.markers)
 4. Seurat:::ScaleData.StdAssay(...)

**Comment by jianhong** [comment]
Please run NormalizeData and retry.

**Comment by vijithaduke** [comment]
sure, will do. thanks!
